create database db_diario_viagem_b;

use db_diario_viagem_b;

-- Tabela de usuários
CREATE TABLE tbl_usuario (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome_completo VARCHAR(50),
    nome_perfil VARCHAR(26),
    email VARCHAR(80) UNIQUE,
    senha VARCHAR(20),
    biografia VARCHAR(200),
    foto_perfil VARCHAR(300),
    data_conta DATE DEFAULT CURRENT_DATE,
    id_sexo INT,
    id_nacionalidade INT,
    FOREIGN KEY (id_sexo) REFERENCES tbl_sexo(id),
    FOREIGN KEY (id_nacionalidade) REFERENCES tbl_nacionalidade(id)
);

-- Tabela de sexo
CREATE TABLE tbl_sexo (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(20)
);

-- Tabela de nacionalidades
CREATE TABLE tbl_nacionalidade (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(70),
    sigla VARCHAR(3)
);

-- Tabela de categorias
CREATE TABLE tbl_categoria (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome_categoria VARCHAR(45)
);

-- Tabela de locais
CREATE TABLE tbl_local (
    id INT PRIMARY KEY AUTO_INCREMENT,
    endereco VARCHAR(200),
    latitude INT,
    longitude INT
);

-- Tabela de viagens
CREATE TABLE tbl_viagem (
    id INT PRIMARY KEY AUTO_INCREMENT,
    id_usuario INT NOT NULL,
    titulo VARCHAR(45),
    descricao VARCHAR(420),
    data_inicio DATE,
    data_fim DATE,
    visibilidade VARCHAR(30),
    data_criacao DATE DEFAULT CURRENT_DATE,
    nota DOUBLE,
    FOREIGN KEY (id_usuario) REFERENCES tbl_usuario(id)
);

-- Tabela de mídias (fotos/vídeos da viagem)
CREATE TABLE tbl_midia (
    id INT PRIMARY KEY AUTO_INCREMENT,
    tipo VARCHAR(20), -- exemplo: 'foto', 'vídeo'
    url VARCHAR(250),
    tbl_viagem_id INT,
    FOREIGN KEY (tbl_viagem_id) REFERENCES tbl_viagem(id)
);

-- Tabela de relacionamento entre viagem e local
CREATE TABLE tbl_viagem_local (
    id INT PRIMARY KEY AUTO_INCREMENT,
    id_local INT,
    id_viagem INT,
    FOREIGN KEY (id_local) REFERENCES tbl_local(id),
    FOREIGN KEY (id_viagem) REFERENCES tbl_viagem(id)
);

-- Tabela de relacionamento entre viagem e categoria
CREATE TABLE tbl_categoria_viagem (
    id INT PRIMARY KEY AUTO_INCREMENT,
    id_categoria INT,
    id_viagem INT,
    FOREIGN KEY (id_categoria) REFERENCES tbl_categoria(id),
    FOREIGN KEY (id_viagem) REFERENCES tbl_viagem(id)
);

-- Tabela de comentários
CREATE TABLE tbl_comentario (
    id INT PRIMARY KEY AUTO_INCREMENT,
    texto VARCHAR(250),
    data DATETIME DEFAULT CURRENT_TIMESTAMP,
    id_usuario INT,
    id_viagem INT,
    FOREIGN KEY (id_usuario) REFERENCES tbl_usuario(id),
    FOREIGN KEY (id_viagem) REFERENCES tbl_viagem(id)
);

-- Tabela de viagens salvas
CREATE TABLE tbl_viagem_salva (
    id INT PRIMARY KEY AUTO_INCREMENT,
    id_viagem_id INT,
    tbl_usuario_id INT,
    data DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_viagem_id) REFERENCES tbl_viagem(id),
    FOREIGN KEY (tbl_usuario_id) REFERENCES tbl_usuario(id)
);

INSERT INTO tbl_nacionalidade (pais, sigla) VALUES
('Afeganistão', 'AFG'),
('África do Sul', 'ZAF'),
('Albânia', 'ALB'),
('Alemanha', 'DEU'),
('Andorra', 'AND'),
('Angola', 'AGO'),
('Anguilla', 'AIA'),
('Antártida', 'ATA'),
('Antígua e Barbuda', 'ATG'),
('Arábia Saudita', 'SAU'),
('Argélia', 'DZA'),
('Argentina', 'ARG'),
('Armênia', 'ARM'),
('Aruba', 'ABW'),
('Austrália', 'AUS'),
('Áustria', 'AUT'),
('Azerbaijão', 'AZE'),
('Bahamas', 'BHS'),
('Bahrein', 'BHR'),
('Bangladesh', 'BGD'),
('Barbados', 'BRB'),
('Belarus', 'BLR'),
('Bélgica', 'BEL'),
('Belize', 'BLZ'),
('Benim', 'BEN'),
('Bermudas', 'BMU'),
('Butão', 'BTN'),
('Bolívia', 'BOL'),
('Bonaire, Sint Eustatius e Saba', 'BES'),
('Bósnia e Herzegovina', 'BIH'),
('Botsuana', 'BWA'),
('Ilha Bouvet', 'BVT'),
('Brasil', 'BRA'),
('Brunei Darussalam', 'BRN'),
('Bulgária', 'BGR'),
('Burkina Faso', 'BFA'),
('Burundi', 'BDI'),
('Cabo Verde', 'CPV'),
('Camboja', 'KHM'),
('Camarões', 'CMR'),
('Canadá', 'CAN'),
('Ilhas Cayman', 'CYM'),
('República Centro-Africana', 'CAF'),
('Chade', 'TCD'),
('Chile', 'CHL'),
('China', 'CHN'),
('Ilha Christmas', 'CXR'),
('Ilhas Cocos (Keeling)', 'CCK'),
('Colômbia', 'COL'),
('Comores', 'COM'),
('Congo (República Democrática do)', 'COD'),
('Congo (República do)', 'COG'),
('Ilhas Cook', 'COK'),
('Coreia (República Popular Democrática da)', 'PRK'),
('Coreia (República da)', 'KOR'),
('Costa do Marfim', 'CIV'),
('Costa Rica', 'CRI'),
('Croácia', 'HRV'),
('Cuba', 'CUB'),
('Curaçao', 'CUW'),
('Chipre', 'CYP'),
('Chéquia', 'CZE'),
('Dinamarca', 'DNK'),
('Djibouti', 'DJI'),
('Dominica', 'DMA'),
('República Dominicana', 'DOM'),
('Equador', 'ECU'),
('Egito', 'EGY'),
('El Salvador', 'SLV'),
('Guiné Equatorial', 'GNQ'),
('Eritreia', 'ERI'),
('Estônia', 'EST'),
('Essuatíni', 'SWZ'),
('Etiópia', 'ETH'),
('Ilhas Falkland (Malvinas)', 'FLK'),
('Ilhas Faroe', 'FRO'),
('Fiji', 'FJI'),
('Finlândia', 'FIN'),
('França', 'FRA'),
('Guiana Francesa', 'GUF'),
('Polinésia Francesa', 'PYF'),
('Territórios Franceses do Sul', 'ATF'),
('Gabão', 'GAB'),
('Gâmbia', 'GMB'),
('Geórgia', 'GEO'),
('Gana', 'GHA'),
('Gibraltar', 'GIB'),
('Grécia', 'GRC'),
('Groenlândia', 'GRL'),
('Granada', 'GRD'),
('Guadalupe', 'GLP'),
('Guam', 'GUM'),
('Guatemala', 'GTM'),
('Guernsey', 'GGY'),
('Guiné', 'GIN'),
('Guiné-Bissau', 'GNB'),
('Guiana', 'GUY'),
('Haiti', 'HTI'),
('Ilha Heard e Ilhas McDonald', 'HMD'),
('Santa Sé (Cidade do Vaticano)', 'VAT'),
('Honduras', 'HND'),
('Hong Kong', 'HKG'),
('Hungria', 'HUN'),
('Islândia', 'ISL'),
('Índia', 'IND'),
('Indonésia', 'IDN'),
('Irã (República Islâmica do)', 'IRN'),
('Iraque', 'IRQ'),
('Irlanda', 'IRL'),
('Ilha de Man', 'IMN'),
('Israel', 'ISR'),
('Itália', 'ITA'),
('Jamaica', 'JAM'),
('Japão', 'JPN'),
('Jersey', 'JEY'),
('Jordânia', 'JOR'),
('Cazaquistão', 'KAZ'),
('Quênia', 'KEN'),
('Kiribati', 'KIR'),
('Kuwait', 'KWT'),
('Quirguistão', 'KGZ'),
('Laos (República Democrática Popular do)', 'LAO'),
('Letônia', 'LVA'),
('Líbano', 'LBN'),
('Lesoto', 'LSO'),
('Libéria', 'LBR'),
('Líbia', 'LBY'),
('Liechtenstein', 'LIE'),
('Lituânia', 'LTU'),
('Luxemburgo', 'LUX'),
('Macau', 'MAC'),
('Madagascar', 'MDG'),
('Malawi', 'MWI'),
('Malásia', 'MYS'),
('Maldivas', 'MDV'),
('Mali', 'MLI'),
('Malta', 'MLT'),
('Ilhas Marshall', 'MHL'),
('Martinica', 'MTQ'),
('Mauritânia', 'MRT'),
('Maurício', 'MUS'),
('Mayotte', 'MYT'),
('México', 'MEX'),
('Micronésia (Estados Federados da)', 'FSM'),
('Moldávia (República da)', 'MDA'),
('Mônaco', 'MCO'),
('Mongólia', 'MNG'),
('Montenegro', 'MNE'),
('Montserrat', 'MSR'),
('Marrocos', 'MAR'),
('Moçambique', 'MOZ'),
('Myanmar', 'MMR'),
('Namíbia', 'NAM'),
('Nauru', 'NRU'),
('Nepal', 'NPL'),
('Países Baixos', 'NLD'),
('Nova Caledônia', 'NCL'),
('Nova Zelândia', 'NZL'),
('Nicarágua', 'NIC'),
('Níger', 'NER'),
('Nigéria', 'NGA'),
('Niue', 'NIU'),
('Ilha Norfolk', 'NFK'),
('Macedônia do Norte', 'MKD'),
('Ilhas Marianas do Norte', 'MNP'),
('Noruega', 'NOR'),
('Omã', 'OMN'),
('Paquistão', 'PAK'),
('Palau', 'PLW'),
('Palestina, Estado da', 'PSE'),
('Panamá', 'PAN'),
('Papua Nova Guiné', 'PNG'),
('Paraguai', 'PRY'),
('Peru', 'PER'),
('Filipinas', 'PHL'),
('Pitcairn', 'PCN'),
('Polônia', 'POL'),
('Portugal', 'PRT'),
('Porto Rico', 'PRI'),
('Catar', 'QAT'),
('Reunião', 'REU'),
('Romênia', 'ROU'),
('Federação Russa', 'RUS'),
('Ruanda', 'RWA'),
('São Bartolomeu', 'BLM'),
('Santa Helena, Ascensão e Tristão da Cunha', 'SHN'),
('São Cristóvão e Neves', 'KNA'),
('Santa Lúcia', 'LCA'),
('São Martinho (Parte Francesa)', 'MAF'),
('São Pedro e Miquelão', 'SPM'),
('São Vicente e Granadinas', 'VCT'),
('Samoa', 'WSM'),
('San Marino', 'SMR'),
('São Tomé e Príncipe', 'STP'),
('Senegal', 'SEN'),
('Sérvia', 'SRB'),
('Seychelles', 'SYC'),
('Serra Leoa', 'SLE'),
('Singapura', 'SGP'),
('Sint Maarten (Parte Holandesa)', 'SXM'),
('Eslováquia', 'SVK'),
('Eslovênia', 'SVN'),
('Ilhas Salomão', 'SLB'),
('Somália', 'SOM'),
('Geórgia do Sul e Ilhas Sandwich do Sul', 'SGS'),
('Sudão do Sul', 'SSD'),
('Espanha', 'ESP'),
('Sri Lanka', 'LKA'),
('Sudão', 'SDN'),
('Suriname', 'SUR'),
('Svalbard e Jan Mayen', 'SJM'),
('Suécia', 'SWE'),
('Suíça', 'CHE'),
('República Árabe Síria', 'SYR'),
('Taiwan, Província da China', 'TWN'),
('Tajiquistão', 'TJK'),
('Tanzânia, República Unida da', 'TZA'),
('Tailândia', 'THA'),
('Timor-Leste', 'TLS'),
('Togo', 'TGO'),
('Tokelau', 'TKL'),
('Tonga', 'TON'),
('Trinidade e Tobago', 'TTO'),
('Tunísia', 'TUN'),
('Turquia', 'TUR'),
('Turcomenistão', 'TKM'),
('Ilhas Turks e Caicos', 'TCA'),
('Tuvalu', 'TUV'),
('Uganda', 'UGA'),
('Ucrânia', 'UKR'),
('Emirados Árabes Unidos', 'ARE'),
('Reino Unido', 'GBR'),
('Estados Unidos', 'USA'),
('Ilhas Menores Distantes dos Estados Unidos', 'UMI'),
('Uruguai', 'URY'),
('Uzbequistão', 'UZB'),
('Vanuatu', 'VUT'),
('Venezuela (República Bolivariana da)', 'VEN'),
('Vietnã', 'VNM'),
('Ilhas Virgens (Britânicas)', 'VGB'),
('Ilhas Virgens (E.U.A.)', 'VIR'),
('Wallis e Futuna', 'WLF'),
('Saara Ocidental', 'ESH'),
('Iêmen', 'YEM'),
('Zâmbia', 'ZMB'),
('Zimbábue', 'ZWE');